# Generated by Django 5.0.6 on 2026-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_status_f1a03a_idx',
            old_name='reservations_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_user_id_56b0f8_idx',
            old_name='reservations_user_idx',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
