# Generated by Django 5.0.6 on 2026-06-09 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packagecategory_transport_tourpackage_capacity_and_more'),
        ('reservations', '0002_rename_reservations_status_idx_reservation_status_f1a03a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.packagecategory')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='InvoicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days', models.PositiveSmallIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_packages', to='reservations.invoice')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_packages', to='packages.tourpackage')),
            ],
            options={
                'verbose_name': 'Factura - Paquete',
                'verbose_name_plural': 'Facturas - Paquetes',
                'unique_together': {('invoice', 'package')},
            },
        ),
    ]
