# Generated by Django 5.0.6 on 2026-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='departure',
            new_name='packages_de_departu_33d1e8_idx',
            old_name='packages_dep_date_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tourpackage',
            new_name='packages_to_categor_d1c0d8_idx',
            old_name='packages_tp_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='tourpackage',
            new_name='packages_to_price_577ff2_idx',
            old_name='packages_tp_price_idx',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Pega una URL de imagen de internet (p. ej. Unsplash, Pexels). Se usará si no hay imagen subida.', max_length=500, null=True, verbose_name='URL de imagen (internet)'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='packagedestination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
