# Generated by Django 5.0.6 on 2026-06-09 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_locations_ci_name_idx_locations_c_name_5719ba_idx_and_more'),
        ('packages', '0002_rename_packages_dep_date_status_idx_packages_de_departu_33d1e8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Categoría de Paquete',
                'verbose_name_plural': 'Categorías de Paquetes',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
            },
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen de internet (Unsplash, Pexels). Se usa si no hay imagen subida.', max_length=500, null=True, verbose_name='URL de imagen'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.packagecategory'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('ruc', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='locations.country')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.provider'),
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='locations.city')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
        migrations.CreateModel(
            name='PackageScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_order', models.PositiveIntegerField(default=1)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_scales', to='packages.tourpackage')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_scales', to='packages.scale')),
            ],
            options={
                'verbose_name': 'Escala del Paquete',
                'verbose_name_plural': 'Escalas del Paquete',
                'ordering': ['visit_order'],
            },
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.transport'),
        ),
        migrations.AddConstraint(
            model_name='packagescale',
            constraint=models.UniqueConstraint(fields=('package', 'scale'), name='unique_package_scale'),
        ),
    ]
