# Generated by Django 5.0.6 on 2026-06-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('cedula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('position', models.CharField(blank=True, max_length=80)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Agente de Venta',
                'verbose_name_plural': 'Agentes de Venta',
            },
        ),
    ]
