# Generated by Django 5.0.6 on 2026-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='destination',
            new_name='destination_name_96ccc3_idx',
            old_name='destinations_name_idx',
        ),
        migrations.RenameIndex(
            model_name='destination',
            new_name='destination_difficu_81c6a6_idx',
            old_name='destinations_diff_idx',
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
