# Generated by Django 5.0.6 on 2026-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='city',
            new_name='locations_c_name_5719ba_idx',
            old_name='locations_ci_name_idx',
        ),
        migrations.RenameIndex(
            model_name='country',
            new_name='locations_c_code_9c92f4_idx',
            old_name='locations_c_code_idx',
        ),
        migrations.RenameIndex(
            model_name='country',
            new_name='locations_c_name_b70dbe_idx',
            old_name='locations_c_name_idx',
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
